package com.management.forutona.PageContentDto;

import java.util.Date;

public class Noticepage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NoticePage.idx
     *
     * @mbg.generated
     */
    private Integer idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NoticePage.pageName
     *
     * @mbg.generated
     */
    private String pageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NoticePage.pageWriter
     *
     * @mbg.generated
     */
    private String pageWriter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NoticePage.writeDate
     *
     * @mbg.generated
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NoticePage.pageContent
     *
     * @mbg.generated
     */
    private String pageContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NoticePage.idx
     *
     * @return the value of NoticePage.idx
     *
     * @mbg.generated
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NoticePage.idx
     *
     * @param idx the value for NoticePage.idx
     *
     * @mbg.generated
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NoticePage.pageName
     *
     * @return the value of NoticePage.pageName
     *
     * @mbg.generated
     */
    public String getPageName() {
        return pageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NoticePage.pageName
     *
     * @param pageName the value for NoticePage.pageName
     *
     * @mbg.generated
     */
    public void setPageName(String pageName) {
        this.pageName = pageName == null ? null : pageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NoticePage.pageWriter
     *
     * @return the value of NoticePage.pageWriter
     *
     * @mbg.generated
     */
    public String getPageWriter() {
        return pageWriter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NoticePage.pageWriter
     *
     * @param pageWriter the value for NoticePage.pageWriter
     *
     * @mbg.generated
     */
    public void setPageWriter(String pageWriter) {
        this.pageWriter = pageWriter == null ? null : pageWriter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NoticePage.writeDate
     *
     * @return the value of NoticePage.writeDate
     *
     * @mbg.generated
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NoticePage.writeDate
     *
     * @param writeDate the value for NoticePage.writeDate
     *
     * @mbg.generated
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NoticePage.pageContent
     *
     * @return the value of NoticePage.pageContent
     *
     * @mbg.generated
     */
    public String getPageContent() {
        return pageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NoticePage.pageContent
     *
     * @param pageContent the value for NoticePage.pageContent
     *
     * @mbg.generated
     */
    public void setPageContent(String pageContent) {
        this.pageContent = pageContent == null ? null : pageContent.trim();
    }
}