package com.management.forutona.FcubeQuestPage;

import java.util.List;

public interface FcubequestpageviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeQuestPageView
     *
     * @mbg.generated
     */
    int insert(Fcubequestpageview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FcubeQuestPageView
     *
     * @mbg.generated
     */
    List<Fcubequestpageview> selectAll();

    List<Fcubequestpageview> selectFcubeQuestPageView(FcubequestpageviewSearchdto searchdto);
    int selectFcubeQuestPageViewlength(FcubequestpageviewSearchdto searchdto);
}