package com.management.forutona.FcubeDao;

import com.management.forutona.FcubeDto.FcubeUserSearchdto;
import com.management.forutona.FcubeDto.FcubeUserinfo;
import java.util.List;

public interface FcubeUserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserInfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserInfo
     *
     * @mbg.generated
     */
    int insert(FcubeUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserInfo
     *
     * @mbg.generated
     */
    FcubeUserinfo selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserInfo
     *
     * @mbg.generated
     */
    List<FcubeUserinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserInfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FcubeUserinfo record);

    List<FcubeUserinfo> selectlistbysearch(FcubeUserSearchdto searchdto);

    int selectFcubeUserinfolength(FcubeUserSearchdto searchdto);
}