package com.management.forutona.FaqPage;

import java.util.List;

public interface FaqpageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FAQPage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FAQPage
     *
     * @mbg.generated
     */
    int insert(Faqpage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FAQPage
     *
     * @mbg.generated
     */
    Faqpage selectByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FAQPage
     *
     * @mbg.generated
     */
    List<Faqpage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FAQPage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Faqpage record);

    List<Faqpage> selectListofsearch(FaqpageSearchdto searchdto);

    int selectListofsearchLength();

}