package com.management.forutona.FaqPage;

import java.util.Date;

public class Faqpage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FAQPage.idx
     *
     * @mbg.generated
     */
    private Integer idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FAQPage.docName
     *
     * @mbg.generated
     */
    private String docName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FAQPage.pageWriter
     *
     * @mbg.generated
     */
    private String pageWriter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FAQPage.writeDate
     *
     * @mbg.generated
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FAQPage.pageContent
     *
     * @mbg.generated
     */
    private String pageContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FAQPage.idx
     *
     * @return the value of FAQPage.idx
     *
     * @mbg.generated
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FAQPage.idx
     *
     * @param idx the value for FAQPage.idx
     *
     * @mbg.generated
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FAQPage.docName
     *
     * @return the value of FAQPage.docName
     *
     * @mbg.generated
     */
    public String getDocName() {
        return docName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FAQPage.docName
     *
     * @param docName the value for FAQPage.docName
     *
     * @mbg.generated
     */
    public void setDocName(String docName) {
        this.docName = docName == null ? null : docName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FAQPage.pageWriter
     *
     * @return the value of FAQPage.pageWriter
     *
     * @mbg.generated
     */
    public String getPageWriter() {
        return pageWriter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FAQPage.pageWriter
     *
     * @param pageWriter the value for FAQPage.pageWriter
     *
     * @mbg.generated
     */
    public void setPageWriter(String pageWriter) {
        this.pageWriter = pageWriter == null ? null : pageWriter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FAQPage.writeDate
     *
     * @return the value of FAQPage.writeDate
     *
     * @mbg.generated
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FAQPage.writeDate
     *
     * @param writeDate the value for FAQPage.writeDate
     *
     * @mbg.generated
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FAQPage.pageContent
     *
     * @return the value of FAQPage.pageContent
     *
     * @mbg.generated
     */
    public String getPageContent() {
        return pageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FAQPage.pageContent
     *
     * @param pageContent the value for FAQPage.pageContent
     *
     * @mbg.generated
     */
    public void setPageContent(String pageContent) {
        this.pageContent = pageContent == null ? null : pageContent.trim();
    }
}