package com.management.forutona.PageContentDao;

import com.management.forutona.PageContentDto.NoticePageSearchDto;
import com.management.forutona.PageContentDto.Noticepage;
import java.util.List;

public interface NoticepageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NoticePage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NoticePage
     *
     * @mbg.generated
     */
    int insert(Noticepage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NoticePage
     *
     * @mbg.generated
     */
    Noticepage selectByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NoticePage
     *
     * @mbg.generated
     */
    List<Noticepage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NoticePage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Noticepage record);

    List<Noticepage> selectlistbysearch(NoticePageSearchDto searchDto);

    int selectPagelength();
}