package com.management.forutona.FcubeDto;

import java.util.Date;

public class Fcubequestpageview {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.Cubeuuid
     *
     * @mbg.generated
     */
    private String cubeuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.Uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.longitude
     *
     * @mbg.generated
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.latitude
     *
     * @mbg.generated
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.CubeName
     *
     * @mbg.generated
     */
    private String cubeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.CubeType
     *
     * @mbg.generated
     */
    private String cubeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.MakeTime
     *
     * @mbg.generated
     */
    private Date makeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.Influence
     *
     * @mbg.generated
     */
    private Double influence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.CubeState
     *
     * @mbg.generated
     */
    private Integer cubeState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.PlaceAddress
     *
     * @mbg.generated
     */
    private String placeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.AdministrativeArea
     *
     * @mbg.generated
     */
    private String administrativeArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.Country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.PointReward
     *
     * @mbg.generated
     */
    private Double pointReward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.InfluenceReward
     *
     * @mbg.generated
     */
    private Double influenceReward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.ActivationTime
     *
     * @mbg.generated
     */
    private Date activationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.CubePassword
     *
     * @mbg.generated
     */
    private String cubePassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.HasPassword
     *
     * @mbg.generated
     */
    private Integer hasPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.CubeScope
     *
     * @mbg.generated
     */
    private Integer cubeScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.InfluenceLevel
     *
     * @mbg.generated
     */
    private Double influenceLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.CubeHits
     *
     * @mbg.generated
     */
    private Integer cubeHits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.CubeLikes
     *
     * @mbg.generated
     */
    private Integer cubeLikes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.CubeDisLikes
     *
     * @mbg.generated
     */
    private Integer cubeDisLikes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.JoinPlayer
     *
     * @mbg.generated
     */
    private Integer joinPlayer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.MaximumPlayers
     *
     * @mbg.generated
     */
    private Integer maximumPlayers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.StarPoints
     *
     * @mbg.generated
     */
    private Double starPoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.ExpGiveFlag
     *
     * @mbg.generated
     */
    private Integer expGiveFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.MakeExp
     *
     * @mbg.generated
     */
    private Double makeExp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.NickName
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.Sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.AgeDate
     *
     * @mbg.generated
     */
    private Date ageDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.Email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.ForutonaAgree
     *
     * @mbg.generated
     */
    private Byte forutonaAgree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.PrivateAgree
     *
     * @mbg.generated
     */
    private Byte privateAgree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.PositionAgree
     *
     * @mbg.generated
     */
    private Byte positionAgree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.MartketingAgree
     *
     * @mbg.generated
     */
    private Byte martketingAgree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FcubeQuestPageView.AgeLimitAgree
     *
     * @mbg.generated
     */
    private Byte ageLimitAgree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.Cubeuuid
     *
     * @return the value of FcubeQuestPageView.Cubeuuid
     *
     * @mbg.generated
     */
    public String getCubeuuid() {
        return cubeuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.Cubeuuid
     *
     * @param cubeuuid the value for FcubeQuestPageView.Cubeuuid
     *
     * @mbg.generated
     */
    public void setCubeuuid(String cubeuuid) {
        this.cubeuuid = cubeuuid == null ? null : cubeuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.Uid
     *
     * @return the value of FcubeQuestPageView.Uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.Uid
     *
     * @param uid the value for FcubeQuestPageView.Uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.longitude
     *
     * @return the value of FcubeQuestPageView.longitude
     *
     * @mbg.generated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.longitude
     *
     * @param longitude the value for FcubeQuestPageView.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.latitude
     *
     * @return the value of FcubeQuestPageView.latitude
     *
     * @mbg.generated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.latitude
     *
     * @param latitude the value for FcubeQuestPageView.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.CubeName
     *
     * @return the value of FcubeQuestPageView.CubeName
     *
     * @mbg.generated
     */
    public String getCubeName() {
        return cubeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.CubeName
     *
     * @param cubeName the value for FcubeQuestPageView.CubeName
     *
     * @mbg.generated
     */
    public void setCubeName(String cubeName) {
        this.cubeName = cubeName == null ? null : cubeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.CubeType
     *
     * @return the value of FcubeQuestPageView.CubeType
     *
     * @mbg.generated
     */
    public String getCubeType() {
        return cubeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.CubeType
     *
     * @param cubeType the value for FcubeQuestPageView.CubeType
     *
     * @mbg.generated
     */
    public void setCubeType(String cubeType) {
        this.cubeType = cubeType == null ? null : cubeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.MakeTime
     *
     * @return the value of FcubeQuestPageView.MakeTime
     *
     * @mbg.generated
     */
    public Date getMakeTime() {
        return makeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.MakeTime
     *
     * @param makeTime the value for FcubeQuestPageView.MakeTime
     *
     * @mbg.generated
     */
    public void setMakeTime(Date makeTime) {
        this.makeTime = makeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.Influence
     *
     * @return the value of FcubeQuestPageView.Influence
     *
     * @mbg.generated
     */
    public Double getInfluence() {
        return influence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.Influence
     *
     * @param influence the value for FcubeQuestPageView.Influence
     *
     * @mbg.generated
     */
    public void setInfluence(Double influence) {
        this.influence = influence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.CubeState
     *
     * @return the value of FcubeQuestPageView.CubeState
     *
     * @mbg.generated
     */
    public Integer getCubeState() {
        return cubeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.CubeState
     *
     * @param cubeState the value for FcubeQuestPageView.CubeState
     *
     * @mbg.generated
     */
    public void setCubeState(Integer cubeState) {
        this.cubeState = cubeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.PlaceAddress
     *
     * @return the value of FcubeQuestPageView.PlaceAddress
     *
     * @mbg.generated
     */
    public String getPlaceAddress() {
        return placeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.PlaceAddress
     *
     * @param placeAddress the value for FcubeQuestPageView.PlaceAddress
     *
     * @mbg.generated
     */
    public void setPlaceAddress(String placeAddress) {
        this.placeAddress = placeAddress == null ? null : placeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.AdministrativeArea
     *
     * @return the value of FcubeQuestPageView.AdministrativeArea
     *
     * @mbg.generated
     */
    public String getAdministrativeArea() {
        return administrativeArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.AdministrativeArea
     *
     * @param administrativeArea the value for FcubeQuestPageView.AdministrativeArea
     *
     * @mbg.generated
     */
    public void setAdministrativeArea(String administrativeArea) {
        this.administrativeArea = administrativeArea == null ? null : administrativeArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.Country
     *
     * @return the value of FcubeQuestPageView.Country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.Country
     *
     * @param country the value for FcubeQuestPageView.Country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.PointReward
     *
     * @return the value of FcubeQuestPageView.PointReward
     *
     * @mbg.generated
     */
    public Double getPointReward() {
        return pointReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.PointReward
     *
     * @param pointReward the value for FcubeQuestPageView.PointReward
     *
     * @mbg.generated
     */
    public void setPointReward(Double pointReward) {
        this.pointReward = pointReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.InfluenceReward
     *
     * @return the value of FcubeQuestPageView.InfluenceReward
     *
     * @mbg.generated
     */
    public Double getInfluenceReward() {
        return influenceReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.InfluenceReward
     *
     * @param influenceReward the value for FcubeQuestPageView.InfluenceReward
     *
     * @mbg.generated
     */
    public void setInfluenceReward(Double influenceReward) {
        this.influenceReward = influenceReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.ActivationTime
     *
     * @return the value of FcubeQuestPageView.ActivationTime
     *
     * @mbg.generated
     */
    public Date getActivationTime() {
        return activationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.ActivationTime
     *
     * @param activationTime the value for FcubeQuestPageView.ActivationTime
     *
     * @mbg.generated
     */
    public void setActivationTime(Date activationTime) {
        this.activationTime = activationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.CubePassword
     *
     * @return the value of FcubeQuestPageView.CubePassword
     *
     * @mbg.generated
     */
    public String getCubePassword() {
        return cubePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.CubePassword
     *
     * @param cubePassword the value for FcubeQuestPageView.CubePassword
     *
     * @mbg.generated
     */
    public void setCubePassword(String cubePassword) {
        this.cubePassword = cubePassword == null ? null : cubePassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.HasPassword
     *
     * @return the value of FcubeQuestPageView.HasPassword
     *
     * @mbg.generated
     */
    public Integer getHasPassword() {
        return hasPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.HasPassword
     *
     * @param hasPassword the value for FcubeQuestPageView.HasPassword
     *
     * @mbg.generated
     */
    public void setHasPassword(Integer hasPassword) {
        this.hasPassword = hasPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.CubeScope
     *
     * @return the value of FcubeQuestPageView.CubeScope
     *
     * @mbg.generated
     */
    public Integer getCubeScope() {
        return cubeScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.CubeScope
     *
     * @param cubeScope the value for FcubeQuestPageView.CubeScope
     *
     * @mbg.generated
     */
    public void setCubeScope(Integer cubeScope) {
        this.cubeScope = cubeScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.InfluenceLevel
     *
     * @return the value of FcubeQuestPageView.InfluenceLevel
     *
     * @mbg.generated
     */
    public Double getInfluenceLevel() {
        return influenceLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.InfluenceLevel
     *
     * @param influenceLevel the value for FcubeQuestPageView.InfluenceLevel
     *
     * @mbg.generated
     */
    public void setInfluenceLevel(Double influenceLevel) {
        this.influenceLevel = influenceLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.CubeHits
     *
     * @return the value of FcubeQuestPageView.CubeHits
     *
     * @mbg.generated
     */
    public Integer getCubeHits() {
        return cubeHits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.CubeHits
     *
     * @param cubeHits the value for FcubeQuestPageView.CubeHits
     *
     * @mbg.generated
     */
    public void setCubeHits(Integer cubeHits) {
        this.cubeHits = cubeHits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.CubeLikes
     *
     * @return the value of FcubeQuestPageView.CubeLikes
     *
     * @mbg.generated
     */
    public Integer getCubeLikes() {
        return cubeLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.CubeLikes
     *
     * @param cubeLikes the value for FcubeQuestPageView.CubeLikes
     *
     * @mbg.generated
     */
    public void setCubeLikes(Integer cubeLikes) {
        this.cubeLikes = cubeLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.CubeDisLikes
     *
     * @return the value of FcubeQuestPageView.CubeDisLikes
     *
     * @mbg.generated
     */
    public Integer getCubeDisLikes() {
        return cubeDisLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.CubeDisLikes
     *
     * @param cubeDisLikes the value for FcubeQuestPageView.CubeDisLikes
     *
     * @mbg.generated
     */
    public void setCubeDisLikes(Integer cubeDisLikes) {
        this.cubeDisLikes = cubeDisLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.JoinPlayer
     *
     * @return the value of FcubeQuestPageView.JoinPlayer
     *
     * @mbg.generated
     */
    public Integer getJoinPlayer() {
        return joinPlayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.JoinPlayer
     *
     * @param joinPlayer the value for FcubeQuestPageView.JoinPlayer
     *
     * @mbg.generated
     */
    public void setJoinPlayer(Integer joinPlayer) {
        this.joinPlayer = joinPlayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.MaximumPlayers
     *
     * @return the value of FcubeQuestPageView.MaximumPlayers
     *
     * @mbg.generated
     */
    public Integer getMaximumPlayers() {
        return maximumPlayers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.MaximumPlayers
     *
     * @param maximumPlayers the value for FcubeQuestPageView.MaximumPlayers
     *
     * @mbg.generated
     */
    public void setMaximumPlayers(Integer maximumPlayers) {
        this.maximumPlayers = maximumPlayers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.StarPoints
     *
     * @return the value of FcubeQuestPageView.StarPoints
     *
     * @mbg.generated
     */
    public Double getStarPoints() {
        return starPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.StarPoints
     *
     * @param starPoints the value for FcubeQuestPageView.StarPoints
     *
     * @mbg.generated
     */
    public void setStarPoints(Double starPoints) {
        this.starPoints = starPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.ExpGiveFlag
     *
     * @return the value of FcubeQuestPageView.ExpGiveFlag
     *
     * @mbg.generated
     */
    public Integer getExpGiveFlag() {
        return expGiveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.ExpGiveFlag
     *
     * @param expGiveFlag the value for FcubeQuestPageView.ExpGiveFlag
     *
     * @mbg.generated
     */
    public void setExpGiveFlag(Integer expGiveFlag) {
        this.expGiveFlag = expGiveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.MakeExp
     *
     * @return the value of FcubeQuestPageView.MakeExp
     *
     * @mbg.generated
     */
    public Double getMakeExp() {
        return makeExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.MakeExp
     *
     * @param makeExp the value for FcubeQuestPageView.MakeExp
     *
     * @mbg.generated
     */
    public void setMakeExp(Double makeExp) {
        this.makeExp = makeExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.NickName
     *
     * @return the value of FcubeQuestPageView.NickName
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.NickName
     *
     * @param nickName the value for FcubeQuestPageView.NickName
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.Sex
     *
     * @return the value of FcubeQuestPageView.Sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.Sex
     *
     * @param sex the value for FcubeQuestPageView.Sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.AgeDate
     *
     * @return the value of FcubeQuestPageView.AgeDate
     *
     * @mbg.generated
     */
    public Date getAgeDate() {
        return ageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.AgeDate
     *
     * @param ageDate the value for FcubeQuestPageView.AgeDate
     *
     * @mbg.generated
     */
    public void setAgeDate(Date ageDate) {
        this.ageDate = ageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.Email
     *
     * @return the value of FcubeQuestPageView.Email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.Email
     *
     * @param email the value for FcubeQuestPageView.Email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.ForutonaAgree
     *
     * @return the value of FcubeQuestPageView.ForutonaAgree
     *
     * @mbg.generated
     */
    public Byte getForutonaAgree() {
        return forutonaAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.ForutonaAgree
     *
     * @param forutonaAgree the value for FcubeQuestPageView.ForutonaAgree
     *
     * @mbg.generated
     */
    public void setForutonaAgree(Byte forutonaAgree) {
        this.forutonaAgree = forutonaAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.PrivateAgree
     *
     * @return the value of FcubeQuestPageView.PrivateAgree
     *
     * @mbg.generated
     */
    public Byte getPrivateAgree() {
        return privateAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.PrivateAgree
     *
     * @param privateAgree the value for FcubeQuestPageView.PrivateAgree
     *
     * @mbg.generated
     */
    public void setPrivateAgree(Byte privateAgree) {
        this.privateAgree = privateAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.PositionAgree
     *
     * @return the value of FcubeQuestPageView.PositionAgree
     *
     * @mbg.generated
     */
    public Byte getPositionAgree() {
        return positionAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.PositionAgree
     *
     * @param positionAgree the value for FcubeQuestPageView.PositionAgree
     *
     * @mbg.generated
     */
    public void setPositionAgree(Byte positionAgree) {
        this.positionAgree = positionAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.MartketingAgree
     *
     * @return the value of FcubeQuestPageView.MartketingAgree
     *
     * @mbg.generated
     */
    public Byte getMartketingAgree() {
        return martketingAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.MartketingAgree
     *
     * @param martketingAgree the value for FcubeQuestPageView.MartketingAgree
     *
     * @mbg.generated
     */
    public void setMartketingAgree(Byte martketingAgree) {
        this.martketingAgree = martketingAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FcubeQuestPageView.AgeLimitAgree
     *
     * @return the value of FcubeQuestPageView.AgeLimitAgree
     *
     * @mbg.generated
     */
    public Byte getAgeLimitAgree() {
        return ageLimitAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FcubeQuestPageView.AgeLimitAgree
     *
     * @param ageLimitAgree the value for FcubeQuestPageView.AgeLimitAgree
     *
     * @mbg.generated
     */
    public void setAgeLimitAgree(Byte ageLimitAgree) {
        this.ageLimitAgree = ageLimitAgree;
    }
}