package com.management.forutona.FcubeDto;

import java.util.Date;

public class Fcube {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.Cubeuuid
     *
     * @mbg.generated
     */
    private String cubeuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.Uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.longitude
     *
     * @mbg.generated
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.latitude
     *
     * @mbg.generated
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.CubeName
     *
     * @mbg.generated
     */
    private String cubeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.CubeType
     *
     * @mbg.generated
     */
    private String cubeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.MakeTime
     *
     * @mbg.generated
     */
    private Date makeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.Influence
     *
     * @mbg.generated
     */
    private Double influence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.CubeState
     *
     * @mbg.generated
     */
    private Integer cubeState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.PlaceAddress
     *
     * @mbg.generated
     */
    private String placeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.AdministrativeArea
     *
     * @mbg.generated
     */
    private String administrativeArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.Country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.PointReward
     *
     * @mbg.generated
     */
    private Double pointReward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.InfluenceReward
     *
     * @mbg.generated
     */
    private Double influenceReward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.ActivationTime
     *
     * @mbg.generated
     */
    private Date activationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.CubePassword
     *
     * @mbg.generated
     */
    private String cubePassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.HasPassword
     *
     * @mbg.generated
     */
    private Integer hasPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.CubeScope
     *
     * @mbg.generated
     */
    private Integer cubeScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.InfluenceLevel
     *
     * @mbg.generated
     */
    private Double influenceLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.CubeHits
     *
     * @mbg.generated
     */
    private Integer cubeHits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.CubeLikes
     *
     * @mbg.generated
     */
    private Integer cubeLikes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.CubeDisLikes
     *
     * @mbg.generated
     */
    private Integer cubeDisLikes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.JoinPlayer
     *
     * @mbg.generated
     */
    private Integer joinPlayer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.MaximumPlayers
     *
     * @mbg.generated
     */
    private Integer maximumPlayers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.StarPoints
     *
     * @mbg.generated
     */
    private Double starPoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.ExpGiveFlag
     *
     * @mbg.generated
     */
    private Integer expGiveFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fcube.MakeExp
     *
     * @mbg.generated
     */
    private Double makeExp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.Cubeuuid
     *
     * @return the value of Fcube.Cubeuuid
     *
     * @mbg.generated
     */
    public String getCubeuuid() {
        return cubeuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.Cubeuuid
     *
     * @param cubeuuid the value for Fcube.Cubeuuid
     *
     * @mbg.generated
     */
    public void setCubeuuid(String cubeuuid) {
        this.cubeuuid = cubeuuid == null ? null : cubeuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.Uid
     *
     * @return the value of Fcube.Uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.Uid
     *
     * @param uid the value for Fcube.Uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.longitude
     *
     * @return the value of Fcube.longitude
     *
     * @mbg.generated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.longitude
     *
     * @param longitude the value for Fcube.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.latitude
     *
     * @return the value of Fcube.latitude
     *
     * @mbg.generated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.latitude
     *
     * @param latitude the value for Fcube.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.CubeName
     *
     * @return the value of Fcube.CubeName
     *
     * @mbg.generated
     */
    public String getCubeName() {
        return cubeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.CubeName
     *
     * @param cubeName the value for Fcube.CubeName
     *
     * @mbg.generated
     */
    public void setCubeName(String cubeName) {
        this.cubeName = cubeName == null ? null : cubeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.CubeType
     *
     * @return the value of Fcube.CubeType
     *
     * @mbg.generated
     */
    public String getCubeType() {
        return cubeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.CubeType
     *
     * @param cubeType the value for Fcube.CubeType
     *
     * @mbg.generated
     */
    public void setCubeType(String cubeType) {
        this.cubeType = cubeType == null ? null : cubeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.MakeTime
     *
     * @return the value of Fcube.MakeTime
     *
     * @mbg.generated
     */
    public Date getMakeTime() {
        return makeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.MakeTime
     *
     * @param makeTime the value for Fcube.MakeTime
     *
     * @mbg.generated
     */
    public void setMakeTime(Date makeTime) {
        this.makeTime = makeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.Influence
     *
     * @return the value of Fcube.Influence
     *
     * @mbg.generated
     */
    public Double getInfluence() {
        return influence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.Influence
     *
     * @param influence the value for Fcube.Influence
     *
     * @mbg.generated
     */
    public void setInfluence(Double influence) {
        this.influence = influence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.CubeState
     *
     * @return the value of Fcube.CubeState
     *
     * @mbg.generated
     */
    public Integer getCubeState() {
        return cubeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.CubeState
     *
     * @param cubeState the value for Fcube.CubeState
     *
     * @mbg.generated
     */
    public void setCubeState(Integer cubeState) {
        this.cubeState = cubeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.PlaceAddress
     *
     * @return the value of Fcube.PlaceAddress
     *
     * @mbg.generated
     */
    public String getPlaceAddress() {
        return placeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.PlaceAddress
     *
     * @param placeAddress the value for Fcube.PlaceAddress
     *
     * @mbg.generated
     */
    public void setPlaceAddress(String placeAddress) {
        this.placeAddress = placeAddress == null ? null : placeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.AdministrativeArea
     *
     * @return the value of Fcube.AdministrativeArea
     *
     * @mbg.generated
     */
    public String getAdministrativeArea() {
        return administrativeArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.AdministrativeArea
     *
     * @param administrativeArea the value for Fcube.AdministrativeArea
     *
     * @mbg.generated
     */
    public void setAdministrativeArea(String administrativeArea) {
        this.administrativeArea = administrativeArea == null ? null : administrativeArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.Country
     *
     * @return the value of Fcube.Country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.Country
     *
     * @param country the value for Fcube.Country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.PointReward
     *
     * @return the value of Fcube.PointReward
     *
     * @mbg.generated
     */
    public Double getPointReward() {
        return pointReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.PointReward
     *
     * @param pointReward the value for Fcube.PointReward
     *
     * @mbg.generated
     */
    public void setPointReward(Double pointReward) {
        this.pointReward = pointReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.InfluenceReward
     *
     * @return the value of Fcube.InfluenceReward
     *
     * @mbg.generated
     */
    public Double getInfluenceReward() {
        return influenceReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.InfluenceReward
     *
     * @param influenceReward the value for Fcube.InfluenceReward
     *
     * @mbg.generated
     */
    public void setInfluenceReward(Double influenceReward) {
        this.influenceReward = influenceReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.ActivationTime
     *
     * @return the value of Fcube.ActivationTime
     *
     * @mbg.generated
     */
    public Date getActivationTime() {
        return activationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.ActivationTime
     *
     * @param activationTime the value for Fcube.ActivationTime
     *
     * @mbg.generated
     */
    public void setActivationTime(Date activationTime) {
        this.activationTime = activationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.CubePassword
     *
     * @return the value of Fcube.CubePassword
     *
     * @mbg.generated
     */
    public String getCubePassword() {
        return cubePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.CubePassword
     *
     * @param cubePassword the value for Fcube.CubePassword
     *
     * @mbg.generated
     */
    public void setCubePassword(String cubePassword) {
        this.cubePassword = cubePassword == null ? null : cubePassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.HasPassword
     *
     * @return the value of Fcube.HasPassword
     *
     * @mbg.generated
     */
    public Integer getHasPassword() {
        return hasPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.HasPassword
     *
     * @param hasPassword the value for Fcube.HasPassword
     *
     * @mbg.generated
     */
    public void setHasPassword(Integer hasPassword) {
        this.hasPassword = hasPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.CubeScope
     *
     * @return the value of Fcube.CubeScope
     *
     * @mbg.generated
     */
    public Integer getCubeScope() {
        return cubeScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.CubeScope
     *
     * @param cubeScope the value for Fcube.CubeScope
     *
     * @mbg.generated
     */
    public void setCubeScope(Integer cubeScope) {
        this.cubeScope = cubeScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.InfluenceLevel
     *
     * @return the value of Fcube.InfluenceLevel
     *
     * @mbg.generated
     */
    public Double getInfluenceLevel() {
        return influenceLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.InfluenceLevel
     *
     * @param influenceLevel the value for Fcube.InfluenceLevel
     *
     * @mbg.generated
     */
    public void setInfluenceLevel(Double influenceLevel) {
        this.influenceLevel = influenceLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.CubeHits
     *
     * @return the value of Fcube.CubeHits
     *
     * @mbg.generated
     */
    public Integer getCubeHits() {
        return cubeHits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.CubeHits
     *
     * @param cubeHits the value for Fcube.CubeHits
     *
     * @mbg.generated
     */
    public void setCubeHits(Integer cubeHits) {
        this.cubeHits = cubeHits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.CubeLikes
     *
     * @return the value of Fcube.CubeLikes
     *
     * @mbg.generated
     */
    public Integer getCubeLikes() {
        return cubeLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.CubeLikes
     *
     * @param cubeLikes the value for Fcube.CubeLikes
     *
     * @mbg.generated
     */
    public void setCubeLikes(Integer cubeLikes) {
        this.cubeLikes = cubeLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.CubeDisLikes
     *
     * @return the value of Fcube.CubeDisLikes
     *
     * @mbg.generated
     */
    public Integer getCubeDisLikes() {
        return cubeDisLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.CubeDisLikes
     *
     * @param cubeDisLikes the value for Fcube.CubeDisLikes
     *
     * @mbg.generated
     */
    public void setCubeDisLikes(Integer cubeDisLikes) {
        this.cubeDisLikes = cubeDisLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.JoinPlayer
     *
     * @return the value of Fcube.JoinPlayer
     *
     * @mbg.generated
     */
    public Integer getJoinPlayer() {
        return joinPlayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.JoinPlayer
     *
     * @param joinPlayer the value for Fcube.JoinPlayer
     *
     * @mbg.generated
     */
    public void setJoinPlayer(Integer joinPlayer) {
        this.joinPlayer = joinPlayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.MaximumPlayers
     *
     * @return the value of Fcube.MaximumPlayers
     *
     * @mbg.generated
     */
    public Integer getMaximumPlayers() {
        return maximumPlayers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.MaximumPlayers
     *
     * @param maximumPlayers the value for Fcube.MaximumPlayers
     *
     * @mbg.generated
     */
    public void setMaximumPlayers(Integer maximumPlayers) {
        this.maximumPlayers = maximumPlayers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.StarPoints
     *
     * @return the value of Fcube.StarPoints
     *
     * @mbg.generated
     */
    public Double getStarPoints() {
        return starPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.StarPoints
     *
     * @param starPoints the value for Fcube.StarPoints
     *
     * @mbg.generated
     */
    public void setStarPoints(Double starPoints) {
        this.starPoints = starPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.ExpGiveFlag
     *
     * @return the value of Fcube.ExpGiveFlag
     *
     * @mbg.generated
     */
    public Integer getExpGiveFlag() {
        return expGiveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.ExpGiveFlag
     *
     * @param expGiveFlag the value for Fcube.ExpGiveFlag
     *
     * @mbg.generated
     */
    public void setExpGiveFlag(Integer expGiveFlag) {
        this.expGiveFlag = expGiveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fcube.MakeExp
     *
     * @return the value of Fcube.MakeExp
     *
     * @mbg.generated
     */
    public Double getMakeExp() {
        return makeExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fcube.MakeExp
     *
     * @param makeExp the value for Fcube.MakeExp
     *
     * @mbg.generated
     */
    public void setMakeExp(Double makeExp) {
        this.makeExp = makeExp;
    }
}