package com.management.forutona.FcubeDto;

import java.util.Date;

public class FcubeUserinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.Uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.NickName
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.ProfilePicktureUrl
     *
     * @mbg.generated
     */
    private String profilePicktureUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.Sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.AgeDate
     *
     * @mbg.generated
     */
    private Date ageDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.Email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.ForutonaAgree
     *
     * @mbg.generated
     */
    private Byte forutonaAgree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.PrivateAgree
     *
     * @mbg.generated
     */
    private Byte privateAgree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.PositionAgree
     *
     * @mbg.generated
     */
    private Byte positionAgree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.MartketingAgree
     *
     * @mbg.generated
     */
    private Byte martketingAgree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.AgeLimitAgree
     *
     * @mbg.generated
     */
    private Byte ageLimitAgree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.SnsService
     *
     * @mbg.generated
     */
    private String snsService;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.Phonenumber
     *
     * @mbg.generated
     */
    private String phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.IsoCode
     *
     * @mbg.generated
     */
    private String isoCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.latitude
     *
     * @mbg.generated
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.longitude
     *
     * @mbg.generated
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.PositionUpdateTime
     *
     * @mbg.generated
     */
    private Date positionUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.UserLevel
     *
     * @mbg.generated
     */
    private Double userLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.ExpPoint
     *
     * @mbg.generated
     */
    private Double expPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.FCMtoken
     *
     * @mbg.generated
     */
    private String FCMtoken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.JoinTime
     *
     * @mbg.generated
     */
    private Date joinTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.Uid
     *
     * @return the value of UserInfo.Uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.Uid
     *
     * @param uid the value for UserInfo.Uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.NickName
     *
     * @return the value of UserInfo.NickName
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.NickName
     *
     * @param nickName the value for UserInfo.NickName
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.ProfilePicktureUrl
     *
     * @return the value of UserInfo.ProfilePicktureUrl
     *
     * @mbg.generated
     */
    public String getProfilePicktureUrl() {
        return profilePicktureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.ProfilePicktureUrl
     *
     * @param profilePicktureUrl the value for UserInfo.ProfilePicktureUrl
     *
     * @mbg.generated
     */
    public void setProfilePicktureUrl(String profilePicktureUrl) {
        this.profilePicktureUrl = profilePicktureUrl == null ? null : profilePicktureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.Sex
     *
     * @return the value of UserInfo.Sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.Sex
     *
     * @param sex the value for UserInfo.Sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.AgeDate
     *
     * @return the value of UserInfo.AgeDate
     *
     * @mbg.generated
     */
    public Date getAgeDate() {
        return ageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.AgeDate
     *
     * @param ageDate the value for UserInfo.AgeDate
     *
     * @mbg.generated
     */
    public void setAgeDate(Date ageDate) {
        this.ageDate = ageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.Email
     *
     * @return the value of UserInfo.Email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.Email
     *
     * @param email the value for UserInfo.Email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.ForutonaAgree
     *
     * @return the value of UserInfo.ForutonaAgree
     *
     * @mbg.generated
     */
    public Byte getForutonaAgree() {
        return forutonaAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.ForutonaAgree
     *
     * @param forutonaAgree the value for UserInfo.ForutonaAgree
     *
     * @mbg.generated
     */
    public void setForutonaAgree(Byte forutonaAgree) {
        this.forutonaAgree = forutonaAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.PrivateAgree
     *
     * @return the value of UserInfo.PrivateAgree
     *
     * @mbg.generated
     */
    public Byte getPrivateAgree() {
        return privateAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.PrivateAgree
     *
     * @param privateAgree the value for UserInfo.PrivateAgree
     *
     * @mbg.generated
     */
    public void setPrivateAgree(Byte privateAgree) {
        this.privateAgree = privateAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.PositionAgree
     *
     * @return the value of UserInfo.PositionAgree
     *
     * @mbg.generated
     */
    public Byte getPositionAgree() {
        return positionAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.PositionAgree
     *
     * @param positionAgree the value for UserInfo.PositionAgree
     *
     * @mbg.generated
     */
    public void setPositionAgree(Byte positionAgree) {
        this.positionAgree = positionAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.MartketingAgree
     *
     * @return the value of UserInfo.MartketingAgree
     *
     * @mbg.generated
     */
    public Byte getMartketingAgree() {
        return martketingAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.MartketingAgree
     *
     * @param martketingAgree the value for UserInfo.MartketingAgree
     *
     * @mbg.generated
     */
    public void setMartketingAgree(Byte martketingAgree) {
        this.martketingAgree = martketingAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.AgeLimitAgree
     *
     * @return the value of UserInfo.AgeLimitAgree
     *
     * @mbg.generated
     */
    public Byte getAgeLimitAgree() {
        return ageLimitAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.AgeLimitAgree
     *
     * @param ageLimitAgree the value for UserInfo.AgeLimitAgree
     *
     * @mbg.generated
     */
    public void setAgeLimitAgree(Byte ageLimitAgree) {
        this.ageLimitAgree = ageLimitAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.SnsService
     *
     * @return the value of UserInfo.SnsService
     *
     * @mbg.generated
     */
    public String getSnsService() {
        return snsService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.SnsService
     *
     * @param snsService the value for UserInfo.SnsService
     *
     * @mbg.generated
     */
    public void setSnsService(String snsService) {
        this.snsService = snsService == null ? null : snsService.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.Phonenumber
     *
     * @return the value of UserInfo.Phonenumber
     *
     * @mbg.generated
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.Phonenumber
     *
     * @param phonenumber the value for UserInfo.Phonenumber
     *
     * @mbg.generated
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.IsoCode
     *
     * @return the value of UserInfo.IsoCode
     *
     * @mbg.generated
     */
    public String getIsoCode() {
        return isoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.IsoCode
     *
     * @param isoCode the value for UserInfo.IsoCode
     *
     * @mbg.generated
     */
    public void setIsoCode(String isoCode) {
        this.isoCode = isoCode == null ? null : isoCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.latitude
     *
     * @return the value of UserInfo.latitude
     *
     * @mbg.generated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.latitude
     *
     * @param latitude the value for UserInfo.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.longitude
     *
     * @return the value of UserInfo.longitude
     *
     * @mbg.generated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.longitude
     *
     * @param longitude the value for UserInfo.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.PositionUpdateTime
     *
     * @return the value of UserInfo.PositionUpdateTime
     *
     * @mbg.generated
     */
    public Date getPositionUpdateTime() {
        return positionUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.PositionUpdateTime
     *
     * @param positionUpdateTime the value for UserInfo.PositionUpdateTime
     *
     * @mbg.generated
     */
    public void setPositionUpdateTime(Date positionUpdateTime) {
        this.positionUpdateTime = positionUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.UserLevel
     *
     * @return the value of UserInfo.UserLevel
     *
     * @mbg.generated
     */
    public Double getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.UserLevel
     *
     * @param userLevel the value for UserInfo.UserLevel
     *
     * @mbg.generated
     */
    public void setUserLevel(Double userLevel) {
        this.userLevel = userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.ExpPoint
     *
     * @return the value of UserInfo.ExpPoint
     *
     * @mbg.generated
     */
    public Double getExpPoint() {
        return expPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.ExpPoint
     *
     * @param expPoint the value for UserInfo.ExpPoint
     *
     * @mbg.generated
     */
    public void setExpPoint(Double expPoint) {
        this.expPoint = expPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.FCMtoken
     *
     * @return the value of UserInfo.FCMtoken
     *
     * @mbg.generated
     */
    public String getFCMtoken() {
        return FCMtoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.FCMtoken
     *
     * @param FCMtoken the value for UserInfo.FCMtoken
     *
     * @mbg.generated
     */
    public void setFCMtoken(String FCMtoken) {
        this.FCMtoken = FCMtoken == null ? null : FCMtoken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.JoinTime
     *
     * @return the value of UserInfo.JoinTime
     *
     * @mbg.generated
     */
    public Date getJoinTime() {
        return joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.JoinTime
     *
     * @param joinTime the value for UserInfo.JoinTime
     *
     * @mbg.generated
     */
    public void setJoinTime(Date joinTime) {
        this.joinTime = joinTime;
    }
}